cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'hashicorp/tap'

brew 'cloudflared'
brew 'imagemagick'
brew 'postgresql@14'
brew 'ruby-build'
brew 'spaceman-diff'
brew 'tfenv'
brew 'uv'
brew 'wget'
brew 'yt-dlp'

cask 'arq'
cask 'claude'
cask 'diffusionbee'
cask 'ghostty'
cask 'handbrake'
cask 'plex'
cask 'sonos'
cask 'transmission'
cask 'raycast'
cask 'warp'
cask 'whatsapp'
cask 'vlc'
cask 'zed'
cask 'zoom'
